var g="aomz_cart";function d(){try{return JSON.parse(localStorage.getItem(g))||{}}catch{return{}}}function u(t){localStorage.setItem(g,JSON.stringify(t))}function a(t){let r=Object.values(t).reduce((n,c)=>n+c.qty,0);document.querySelectorAll(".header__cart-badge").forEach(n=>{n.textContent=r})}function v(t){let r=t.replace(/\D/g,"");return r?parseInt(r,10):null}function f(t){return`${t.toLocaleString("ru-RU")}\xA0\u20BD`}function s(t){let r=document.getElementById("cart-summary"),n=document.getElementById("cart-summary-count"),c=document.getElementById("cart-summary-price-row"),o=document.getElementById("cart-summary-price"),e=Object.entries(t);if(!e.length){r.classList.remove("cart-order__summary--visible");return}r.classList.add("cart-order__summary--visible");let q=e.reduce((l,[,i])=>l+i.qty,0);n.textContent=q;let p=e.reduce((l,[,i])=>{let b=v(i.priceText);return b!==null?l+b*i.qty:l},0);o.textContent=p>0?`\u043E\u0442\xA0${f(p)}`:"\u043F\u043E\xA0\u0437\u0430\u043F\u0440\u043E\u0441\u0443",c.classList.add("cart-order__summary-price-row--visible")}function y(t){let r=document.getElementById("cart-empty"),n=Object.keys(t).length===0;r.classList.toggle("cart-order__empty--visible",n)}function m(t){return t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function E(t,r){let n=document.createElement("li");n.className="cart-item";let c=r.url?`<a class="cart-item__name-link" href="${m(r.url)}">${m(r.name)}</a>`:m(r.name);n.innerHTML=`
    <div class="cart-item__info">
      <h3 class="cart-item__name">${c}</h3>
      <p class="cart-item__price">${m(r.priceText)}</p>
    </div>
    <div class="cart-item__qty" aria-label="\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0442\u043E\u0432\u0430\u0440\u0430">
      <button class="cart-item__qty-btn cart-item__qty-btn--minus" type="button" aria-label="\u0423\u043C\u0435\u043D\u044C\u0448\u0438\u0442\u044C \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E">\u2212</button>
      <span class="cart-item__qty-value" aria-live="polite">${r.qty}</span>
      <button class="cart-item__qty-btn cart-item__qty-btn--plus" type="button" aria-label="\u0423\u0432\u0435\u043B\u0438\u0447\u0438\u0442\u044C \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E">+</button>
    </div>
    <button class="cart-item__remove" type="button" aria-label="\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0442\u043E\u0432\u0430\u0440 \u0438\u0437 \u043A\u043E\u0440\u0437\u0438\u043D\u044B"></button>
  `;let o=n.querySelector(".cart-item__qty-value");return n.querySelector(".cart-item__qty-btn--minus").addEventListener("click",()=>{let e=d();e[t]&&(e[t].qty-=1,e[t].qty<=0?(delete e[t],u(e),a(e),n.remove(),y(e),s(e)):(u(e),a(e),o.textContent=e[t].qty,s(e)))}),n.querySelector(".cart-item__qty-btn--plus").addEventListener("click",()=>{let e=d();e[t]&&(e[t].qty+=1,u(e),a(e),o.textContent=e[t].qty,s(e))}),n.querySelector(".cart-item__remove").addEventListener("click",()=>{let e=d();delete e[t],u(e),a(e),n.remove(),y(e),s(e)}),n}function _(){let t=d(),r=document.getElementById("cart-list");r&&(r.innerHTML="",Object.entries(t).forEach(([n,c])=>{r.appendChild(E(n,c))}),y(t),s(t),a(t))}function L(){_()}document.addEventListener("DOMContentLoaded",L);document.addEventListener("cart:submitted",_);window.addEventListener("pageshow",t=>{t.persisted&&_()});
