var p="js-lightbox",n=[],d=0,f=null,e=null,r=null,a=null,s=null;function m(){e=document.createElement("div"),e.className="lightbox",e.setAttribute("role","dialog"),e.setAttribute("aria-modal","true"),e.setAttribute("aria-label","\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439"),e.hidden=!0,e.innerHTML=`
    <div class="lightbox__backdrop"></div>
    <button class="lightbox__prev" type="button" aria-label="\u041F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0435\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435"></button>
    <div class="lightbox__media">
      <img class="lightbox__image" src="" alt="">
    </div>
    <button class="lightbox__next" type="button" aria-label="\u0421\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435"></button>
    <button class="lightbox__close" type="button" aria-label="\u0417\u0430\u043A\u0440\u044B\u0442\u044C"></button>
  `,document.body.appendChild(e),r=e.querySelector(".lightbox__image"),a=e.querySelector(".lightbox__prev"),s=e.querySelector(".lightbox__next"),e.querySelector(".lightbox__backdrop").addEventListener("click",u),e.querySelector(".lightbox__close").addEventListener("click",u),a.addEventListener("click",g),s.addEventListener("click",v),document.addEventListener("keydown",x),e.addEventListener("keydown",t=>{if(t.key!=="Tab")return;let l=[...e.querySelectorAll("button")].filter(c=>!c.hidden);if(!l.length)return;let o=l[0],i=l[l.length-1];t.shiftKey&&document.activeElement===o?(t.preventDefault(),i.focus()):!t.shiftKey&&document.activeElement===i&&(t.preventDefault(),o.focus())})}function _(){let t=n.length>1;a.hidden=!t,s.hidden=!t}function b(t){d=t,r.src=n[t].src,r.alt=n[t].alt,_()}function E(t,l){e||m(),f=document.activeElement,n=t,b(l),e.hidden=!1,document.documentElement.classList.add("is-modal-open"),document.body.style.overflow="hidden",e.querySelector(".lightbox__close").focus()}function u(){e.hidden=!0,document.documentElement.classList.remove("is-modal-open"),document.body.style.overflow="",n=[],f?.focus()}function g(){b((d-1+n.length)%n.length)}function v(){b((d+1)%n.length)}function x(t){if(!e.hidden)switch(t.key){case"Escape":u();break;case"ArrowLeft":n.length>1&&g();break;case"ArrowRight":n.length>1&&v();break}}function k(){let t=document.querySelectorAll(`.${p}`);t.length&&(m(),t.forEach(l=>{let o=[...l.querySelectorAll("img")];o.forEach((i,c)=>{i.addEventListener("click",()=>{let y=o.map(h=>({src:h.src,alt:h.alt}));E(y,c)})})}))}document.addEventListener("DOMContentLoaded",k);export{E as open};
