var q="js-lightbox",c=[],g=0,y=null,t=null,m=null,b=null,f=null;function E(){t=document.createElement("div"),t.className="lightbox",t.setAttribute("role","dialog"),t.setAttribute("aria-modal","true"),t.setAttribute("aria-label","\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439"),t.hidden=!0,t.innerHTML=`
    <div class="lightbox__backdrop"></div>
    <button class="lightbox__prev" type="button" aria-label="\u041F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0435\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435"></button>
    <div class="lightbox__media">
      <img class="lightbox__image" src="" alt="">
    </div>
    <button class="lightbox__next" type="button" aria-label="\u0421\u043B\u0435\u0434\u0443\u044E\u0449\u0435\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435"></button>
    <button class="lightbox__close" type="button" aria-label="\u0417\u0430\u043A\u0440\u044B\u0442\u044C"></button>
  `,document.body.appendChild(t),m=t.querySelector(".lightbox__image"),b=t.querySelector(".lightbox__prev"),f=t.querySelector(".lightbox__next"),t.querySelector(".lightbox__backdrop").addEventListener("click",_),t.querySelector(".lightbox__close").addEventListener("click",_),b.addEventListener("click",L),f.addEventListener("click",S),document.addEventListener("keydown",A),t.addEventListener("keydown",e=>{if(e.key!=="Tab")return;let r=[...t.querySelectorAll("button")].filter(i=>!i.hidden);if(!r.length)return;let n=r[0],l=r[r.length-1];e.shiftKey&&document.activeElement===n?(e.preventDefault(),l.focus()):!e.shiftKey&&document.activeElement===l&&(e.preventDefault(),n.focus())})}function k(){let e=c.length>1;b.hidden=!e,f.hidden=!e}function p(e){g=e,m.src=c[e].src,m.alt=c[e].alt,k()}function v(e,r){t||E(),y=document.activeElement,c=e,p(r),t.hidden=!1,document.documentElement.classList.add("is-modal-open"),document.body.style.overflow="hidden",t.querySelector(".lightbox__close").focus()}function _(){t.hidden=!0,document.documentElement.classList.remove("is-modal-open"),document.body.style.overflow="",c=[],y?.focus()}function L(){p((g-1+c.length)%c.length)}function S(){p((g+1)%c.length)}function A(e){if(!t.hidden)switch(e.key){case"Escape":_();break;case"ArrowLeft":c.length>1&&L();break;case"ArrowRight":c.length>1&&S();break}}function w(){let e=document.querySelectorAll(`.${q}`);e.length&&(E(),e.forEach(r=>{let n=[...r.querySelectorAll("img")];n.forEach((l,i)=>{l.addEventListener("click",()=>{let d=n.map(o=>({src:o.src,alt:o.alt}));v(d,i)})})}))}document.addEventListener("DOMContentLoaded",w);var x=sessionStorage.getItem("editMode")==="true",s=document.querySelector(".product-hero");if(s){let e=s.querySelector("[data-main-image]"),r=s.querySelector(".product-hero__image-button"),n=s.querySelectorAll(".product-hero__thumbnail");if(e&&n.length>0){let l=s.querySelectorAll(".product-hero__thumbnail--active"),i=n[0];(l.length!==1||l[0]!==i)&&(l.forEach(o=>{o.classList.remove("product-hero__thumbnail--active")}),i.classList.add("product-hero__thumbnail--active"));let d=s.querySelector(".product-hero__thumbnail--active");if(d){let o=d.querySelector(".product-hero__thumbnail-image");o&&(e.src=o.src,e.alt=o.alt)}x&&n.forEach(o=>{o.classList.remove("product-hero__thumbnail--active")}),n.forEach(o=>{o.addEventListener("click",()=>{let u=o.querySelector(".product-hero__thumbnail-image"),a=u.src;a&&e&&(e.src=a,e.alt=u.alt,x||(n.forEach(h=>{h.classList.remove("product-hero__thumbnail--active")}),o.classList.add("product-hero__thumbnail--active")))})}),r&&r.addEventListener("click",()=>{let o=Array.from(n).map(a=>{let h=a.querySelector(".product-hero__thumbnail-image");return{src:h.src,alt:h.alt}}),u=Array.from(n).findIndex(a=>a.classList.contains("product-hero__thumbnail--active"));v(o,u!==-1?u:0)})}}
